apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-manager-role
  namespace: devops
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "events", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-manager-binding
  namespace: devops
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: devops
roleRef:
  kind: Role
  name: jenkins-manager-role
  apiGroup: rbac.authorization.k8s.io